[build]
  publish = "Vault.Web/bin/Release/net8.0/publish/wwwroot"
  command = "dotnet publish Vault.Web -c Release -o Vault.Web/bin/Release/net8.0/publish"

[build.environment]
  DOTNET_VERSION = "8.0.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
