version: 2
build:
  commands:
    - dotnet restore
    - dotnet publish Vault.API -c Release -o /app
  watch:
    - "**/*.cs"
    - "**/*.csproj"
start:
  command: dotnet /app/Vault.API.dll
healthcheck:
  command: curl -f http://localhost:$PORT/health || exit 1
  interval: 30s
  timeout: 10s
  retries: 3
